# Set the prefix key to Ctrl+Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g mouse on

unbind-key r 
bind r source-file ~/.config/tmux/tmux.conf
unbind v
unbind h 
unbind %
unbind '"'
bind v split-window -h -c "${pane_current_path}"
bind h split-window -v -c "${pane_current_path}"

set -g status-left-length 50
set -g status-right "#H | %Y-%m-%d %H:%M:%S"
set -g status-left ' #{?client_prefix,#[reverse][x]close [v/h]split pane [r]reload #[noreverse] ,}"

set -g @plugin 'tmux-plugins/tmux-sensible'
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle
bind -t vi-copy y copy-pipe "xclip -sel clip -i"
